### ISSUE TITLE
Дополнение к документации интеграций c yeastar

### ISSUE THREAD

**Issue by streltsovdenis** [CallbeeIO/callbee_wiki#24]
Необходимо описать, что при слепом трансфере станции записывают только 2 часть вызова, соответственно запись с первым поговорившим не будет сохранена. Даже если включена настройка записи целой линии. Необходимо сообщать в support yeastar.
При трансфере с сопровождением будет корректно записана вся линия (необходимо чтобы была включена запись линии) и проброшена запись всей линии в CRM на последнего поговорившего в версии интеграции начиная с v2.0

**Comment by streltsovdenis** [comment]
Перехват вызова будет реализован в версии начиная с версии v2.0

**Comment by Elefuntik** [comment]
Добавить в раздел "4.3 Настройка записей разговоров"
